### ISSUE TITLE
How to use pyopenms.FeatureFindingMetabo() for peak picking?

### ISSUE THREAD

**Issue by sorenwacker** [uweschmitt/pyOpenMS#1]
I found the [documentation](https://pyopenms.readthedocs.io/en/latest/feature_detection.html?highlight=featurefinder) on pyOpenMS mass spec library. I want to try different peak picking algorithms. Unfortunately, the docs are not very detailed and don't show how to use the other peak picking algorithms and the code base itself is also quite difficult to understand.

Is it possible to use, for example, the FeatureFindingMetabo algorithm instead of the centroided one? Are there examples stored somewhere?

**Comment by uweschmitt** [comment]
@hroest can you comment on this?

**Comment by sorenwacker** [comment]
Is there a community for *pyopenms* with a forum where I can post this question?

**Comment by uweschmitt** [comment]
Not that I'm aware of. The feature finder metabo is also wrappend in https://emzed.ethz.ch/3/emzed

**Comment by hroest** [comment]
@soerendip the community for OpenMS and pyOpenMS is overlapping and mainly at OpenMS/OpenMS. I currently do not have examples for the FeatureFinderMetabo but a good place to start is https://github.com/OpenMS/OpenMS/blob/8be3ba98d4e77c2429b7faa0acb13825c18c24a0/src/pyOpenMS/pxds/FeatureFindingMetabo.pxd and the C++ documentation here https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1FeatureFindingMetabo.html and https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/classOpenMS_1_1MassTraceDetection.html

so you should be able to do something like this: 

```
mtdet = MassTraceDetection ()
ffmet = FeatureFindingMetabo()
traces = []
output = FeatureMap()
output_chroms = []

mtdet.run(input, traces, 0)
ffmet.run(traces, output, output_chroms)
```

**Comment by sorenwacker** [comment]
Thank you!! I am not quite sure if everything that I apply makes totally sense, but I can run FFM now across a larger dataset and detect peaks.
